[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "runtime"
path = "src/main.rs"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = "0.8.5"
